### ISSUE TITLE
Missing info.json

### ISSUE THREAD

**Issue by d3x0r** [Hermios/Factorio-Model#1]
info.json files are missing :)

**Comment by Hermios** [comment]
Hey
well, I just added them (Problem with GitIgnore)
Btw, I solved your rails issues : Send a remote request to my mode, with the keyword addRail, and the name of your rails. Then, when adding them, the system will considere them as with power.
Only restriction : Theire names have to start with "curve-" and "straight-". Otherwise, it won't add anything (and give a crash?)

**Comment by d3x0r** [comment]
Sounds reasonable.
